monolog:
    channels: [ 'setter_channel' ]
    handlers:
        setter_channel:
            level: debug
            type: stream
            path:     '%kernel.logs_dir%/setter.log'
            channels: [ 'setter_channel' ]